# Generated by Django 2.1 on 2018-09-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(upload_to='org/teacher/%Y/%m', verbose_name='头像'),
        ),
    ]
